version: "2"

# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

  # include test files or not, default is true
  tests: true

# output configuration options
output:
  formats:
    text:
      path: stdout

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

# be careful when disabling linters. it might affect the quality of the code
# might be better to spend time on refactoring code to follow linting rules
linters:
  default: all
  disable:
    - wsl
    - mnd
    - err113
    - wrapcheck
    - errorlint
    - lll
    - testpackage
    - dupl
    - funlen
    - godot
    - paralleltest
    - tagliatelle
    - revive
    - unparam
    - cyclop
    - gomoddirectives
    - govet
    - nestif
    - forcetypeassert
    - gochecknoglobals
    - depguard
    - inamedparam
    - varnamelen
    - exhaustruct
    - nlreturn
    - ireturn
    - nonamedreturns
    - tagalign
    - gosmopolitan
    - gochecknoinits
    - musttag
    - nolintlint
    - intrange
    - recvcheck
    - embeddedstructfieldcheck
    - noinlineerr
    - perfsprint
    - protogetter
    - noctx
    - testifylint
    - gocritic
    - staticcheck
    - gosec
    - wsl_v5

  settings:
    goheader:
      values:
        regexp:
          YEAR: (2018|2019|2020|2021|2022|2023|2024|2025)(-)?(2019|2020|2021|2022|2023|2024|2025|2026)?
      template: |-
        Copyright (c) {{ YEAR }} AccelByte Inc. All Rights Reserved.
        This is licensed software from AccelByte Inc, for limitations
        and restrictions contact your company contract manager.

formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax

issues:
  exclude:
    - ^G104
    - ^G501
  max-same-issues: 20
