services:
  app:
    build: .
    ports:
      - "6565:6565"
      - "8080:8080"
      - "8000:8000"
    env_file:
      - .env
    environment:
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://host.docker.internal:9411/api/v2/spans # Zipkin
      - OTEL_SERVICE_NAME=PongService
      # - GRPC_GO_LOG_VERBOSITY_LEVEL="99" # enable to debug grpc
      # - GRPC_GO_LOG_SEVERITY_LEVEL=info # enable to debug grpc
    extra_hosts:
      - host.docker.internal:host-gateway
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: http://host.docker.internal:3100/loki/api/v1/push
    #     mode: non-blocking
    #     max-buffer-size: 4m
    #     loki-retries: "3"